demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

demo/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.posts_list, name="list"),
    path("new-post/", views.post_new, name="new-post"),
    path("<slug:slug>", views.post_page, name="page"),
]

demo/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.users_register, name="register"),
    path('login/', views.users_login, name="login"),
    path('logout/', views.users_logout, name="logout"),
]

demo/posts/models.py
from django.db import models

# Create your models here.
# for databases

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.jpg', blank=True)

    def __str__(self) -> str:
        return self.title

demo/users/models.py
from django.db import models

# Create your models here.

demo/demo/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("HELLO WORLD!!!")
    return render(request, 'home.html')

def about(request):
    #return HttpResponse("My About Page.")
    return render(request, 'about.html')

demo/posts/views.py
from django.shortcuts import render
from . models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', { 'posts' : posts})

def post_page(request,slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', { 'post' : post})

@login_required(login_url='/users/login/')
def post_new(request):
    return render(request, 'posts/post_new.html')

demo/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def users_register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def users_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def users_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")
    

demo/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
    </section>
{% endblock %}

demo/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <img 
            class = "banner"
            src="{{ post.banner.url }}"
            alt="{{ post.title }}" 
        />
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

demo/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
        <h1>Posts</h1>

        {% for post in posts %}
            <article class = 'post'>
                <h2>
                    <a href = "{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

demo/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <script src="{% static '/js/main.js' %}" defer></script>
</head>
<body>
    <h1>About</h1>
    <p>Check <a href="/">Home</a></p>
</body>
</html>

demo/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check <a href="/about">About</a></p>
{% endblock %}

demo/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static '/js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href ="/">Home</a> |
        <a href ="/about">About</a> |
        <a href ="{% url 'posts:list' %}">News</a> | 
        
        {% if user.is_authenticated %}
            <a href ="{% url 'posts:new-post' %}">New Post</a> | 
            
            <form class = "logout" action="{% url 'users:logout' %}" method = "post">
                {% csrf_token %}
                <button class="logout-button">LogOut</button>
            </form>
        {% else %}
            <a href ="{% url 'users:register' %}">Register</a> | 
            <a href ="{% url 'users:login' %}">Login</a>    
        {% endif %}

    </nav>
    <main>
        {% block content %}

        {% endblock %}
    </main>
</body>
</html>

demo/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock  %}

{% block content %}
    <section>
        <h1>Login</h1>
        <form class = "form-width-validation" action="/users/login/" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}"/>
            {% endif %}
            <button class= "form-submit">Submit</button>
        </form>
    </section>
{% endblock %}

demo/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    Register New User
{% endblock  %}

{% block content %}
    <section>
        <h1>Register New User</h1>
    </section>
{% endblock %}